//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryCoolerDiagnostic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryCoolerDiagnostic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connect_icon {
            get {
                object obj = ResourceManager.GetObject("connect_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;J_1_Sys_environment_temp&quot;,
        ///    &quot;Message&quot;: &quot;BTMS_BxCool_2_circuits&quot;,
        ///    &quot;Multiplexing/Group&quot;: &quot;0x1&quot;,
        ///    &quot;Startbit&quot;: &quot;8&quot;,
        ///    &quot;Length [Bit]&quot;: &quot;16&quot;,
        ///    &quot;Byte Order&quot;: &quot;Intel&quot;,
        ///    &quot;Value Type&quot;: &quot;Signed&quot;,
        ///    &quot;Initial Value&quot;: &quot;0&quot;,
        ///    &quot;Factor&quot;: &quot;0.1&quot;,
        ///    &quot;Offset&quot;: &quot;0&quot;,
        ///    &quot;Minimum&quot;: &quot;0&quot;,
        ///    &quot;Maximum&quot;: &quot;0&quot;,
        ///    &quot;Value Table&quot;: &quot;&lt;none&gt;&quot;,
        ///    &quot;Comment&quot;: &quot;Job 1, System: Environment temperature&quot;,
        ///    &quot;Message ID&quot;: &quot;0x5DC&quot;,
        ///    &quot;Unit&quot;: &quot;°C&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;J_11_C1_cool [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] parametr {
            get {
                object obj = ResourceManager.GetObject("parametr", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
